#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os
import subprocess

host = subprocess.run(['hostname', '-f'], text=True, capture_output=True).stdout.strip()
config = {"fqdn": host, "path": os.environ['PROMETHEUS_PATH']}

json.dump(config, fp=sys.stdout)
